/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as graphql from "@nestjs/graphql";
import { GraphQLError } from "graphql";
import { isRecordNotFoundError } from "../../prisma.util";
import { MetaQueryPayload } from "../../util/MetaQueryPayload";
import { Architect } from "./Architect";
import { ArchitectCountArgs } from "./ArchitectCountArgs";
import { ArchitectFindManyArgs } from "./ArchitectFindManyArgs";
import { ArchitectFindUniqueArgs } from "./ArchitectFindUniqueArgs";
import { DeleteArchitectArgs } from "./DeleteArchitectArgs";
import { ArchitectService } from "../architect.service";
@graphql.Resolver(() => Architect)
export class ArchitectResolverBase {
  constructor(protected readonly service: ArchitectService) {}

  async _architectsMeta(
    @graphql.Args() args: ArchitectCountArgs
  ): Promise<MetaQueryPayload> {
    const result = await this.service.count(args);
    return {
      count: result,
    };
  }

  @graphql.Query(() => [Architect])
  async architects(
    @graphql.Args() args: ArchitectFindManyArgs
  ): Promise<Architect[]> {
    return this.service.architects(args);
  }

  @graphql.Query(() => Architect, { nullable: true })
  async architect(
    @graphql.Args() args: ArchitectFindUniqueArgs
  ): Promise<Architect | null> {
    const result = await this.service.architect(args);
    if (result === null) {
      return null;
    }
    return result;
  }

  @graphql.Mutation(() => Architect)
  async deleteArchitect(
    @graphql.Args() args: DeleteArchitectArgs
  ): Promise<Architect | null> {
    try {
      return await this.service.deleteArchitect(args);
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new GraphQLError(
          `No resource was found for ${JSON.stringify(args.where)}`
        );
      }
      throw error;
    }
  }
}
